### ISSUE TITLE
build command times out before ESO container is created

### ISSUE THREAD

**Issue by znuggz** [CoinageCrypto/lamington#271]
I am trying to build and the process keeps failing because it times out before the EOS container is up and running. I cannot find anywhere to up the wait time or wait indefinitely until EOS container is ready.

yarn run build --> lamington build

thanks!

Gabriels-MBP:skygrid-dapp gabe$ yarn run build
yarn run v1.17.3
$ lamington build
⠼ Starting EOS docker containerREPOSITORY          TAG                                          IMAGE ID            CREATED             SIZE
lamington           eos.v1.8.6-cdt.v1.6.1-contracts.v1.8.0-rc1   5476bb39c8a0        3 hours ago         967MB
⠦ Starting EOS docker container6e22a0cfec884a6be7585cbe63d6d7256cbe6fccce9bd28ca589a8bc7802b542
✔ Starting EOS docker container
✖ Failed to connect with an EOS instance
 --> Error: Could not contact EOS after trying for 20 second(s).
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by thekevinbrown** [comment]
It really shouldn't take more than 20 seconds to connect to EOS after the docker container is up and running, so I suspect increasing the timeout won't help.

Can you start the docker container yourself outside of lamington to see if EOS is indeed running in there?

**Comment by thekevinbrown** [comment]
I'll assume this is resolved at this point. If you still need help feel free to open a new issue.
