### ISSUE TITLE
`.lamingtonignore` does not seem to work to exclude files from lamington

### ISSUE THREAD

**Issue by dallasjohnson** [CoinageCrypto/lamington#65]
I have created a file in the root of my project with the name `.lamingtonignore` and after adding a few file name to the  file eg. `config.cpp` `lamington build` still attempts to compile it as an independent contract. This and a few other files are smaller parts of a larger contract which are imported into the main contract to compile.

**Comment by MitchPierias** [comment]
Thanks @dallasjohnson, I'll have a look into this soon and get back to you

**Comment by dallasjohnson** [comment]
Thank you. 👍

**Comment by MitchPierias** [comment]
No problem. We are in very early stages, so really appreciate you raising any issues or bugs you find along the way. If you'd like to discuss features or non-issue related things with the project, feel free to join [our Lamington slack channel](https://forms.gle/yTjNA46oKywaD7FR6).
