### ISSUE TITLE
[cli] Custom compile options

### ISSUE THREAD

**Issue by dallasjohnson** [CoinageCrypto/lamington#66]
I am working on a project with several inter-related contracts [EOSDac](https://github.com/eosdac/eosdac-contracts) and have relied on my own custom web of Ruby scripts to to build integration tests around them. Some contracts have compile time options passed in as compiler flags to reduce runtime mutability and increase security of the contracts. For me the standard `compile_contract.sh` script is not adequate and I would like to have the option to override on a per contract basis. A suggestion could be to have a check in the `build` action to see if there is a `compile_contract.sh` in the same folder a contract for compilation and then use that instead. Another thought, perhaps the lamington init command could seed `compile_contract.sh` script into each directory where there is a compilable contract candidate and then devs could alter script to suit them. That could also provide a nice way to opt-in to contract compiling rather than opt-out as with the current "exclude" model.

**Comment by thekevinbrown** [comment]
Hey there, thanks for the feedback!

Could you give us a couple of examples of the options you want to pass in so I can fully understand your use case? There are several places I can think of that we could inject this config, so really just want to understand how you're using the options so where you configure them makes the most sense.

**Comment by dallasjohnson** [comment]
Here's an example of how I have been using compile time flags. https://github.com/eosdac/eosdac-contracts/blob/e951560ae0dd388ada3280ddcb97148a92dfc099/_compiled_contracts/daccustodian/jungle/compile.sh#L4. Also note that I had needed to add `-I.` to the compile command to help with importing headers. I'm not sure if this is still required but there are many options available for the compiler  which may be needed for different projects. Therefore the open you can make this the better IMHO.

**Comment by mwawrusch** [comment]
+1 for this as well. RAM is super expensive so we try to optimize as much as possible - in our case:
```
-Os -finline-hint-functions -fno-elide-constructors
```

**Comment by dallasjohnson** [comment]
From my perspective this issue can be closed since I have added the fixes I needed in #204 @mwawrusch Not sure if the changes would help you also

**Comment by thekevinbrown** [comment]
`lamington@1.0.0-alpha.5` has been published. If this doesn't solve the issue please let us know in a new issue.
